name: Auto build package with NSI Installer
on:
  create:
    tags:
      - v*
jobs: 
  build:
    name: Build Ren'py project
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout 
        uses: actions/checkout@v1

      - name: Build Ren'Py Project
        uses: ProjectAliceDev/renpy-build-action@master
        id: build-renpy
        with:
          sdk-version: '7.4.11'
          project-dir: '.'
          package: pc
        env: 
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy

      - name: Upload artifact to GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: renpy-artifact
          path: ${{steps.build-renpy.outputs.dir}}
  installer:
    name: Create Installer for RenPy Project
    runs-on: ubuntu-latest
    needs: build
    env:
      INSTALLER_PATH: "FPTUFIA AnIsSus Setup.exe"
    steps:
      - name: Install required library
        run: |
          sudo apt update
          sudo apt install -y nsis
      - name: Download artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: renpy-artifact
          path: ./artifact/
      - name: Unzip Artifact file
        run: unzip AnIsSus-Sus.Sus-pc.zip
      - name: Create Installer
        uses: joncloud/makensis-action@v3.6
        with: 
          script-file: "./artifact/AnIsSus-Sus.Sus-pc/install.nsi"
      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with: 
          name: final-artifact
          path: ./artifact/AnIsSus-Sus.Sus-pc/${INSTALLER_PATH}
        
