name: Auto build package with NSI Installer
on:
  create:
    tags:
      - v*
jobs: 
  build:
    name: Build Ren'py project
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout 
        uses: actions/checkout@v1

      - name: Build Ren'Py Project
        uses: ProjectAliceDev/renpy-build-action@master
        id: build-renpy
        with:
          sdk-version: '7.4.11'
          project-dir: '.'
        env: 
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy

      - name: Upload artifact to GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: renpy-artifact
          path: ${{steps.build-renpy.outputs.dir}}
